sudo: required
dist: trusty
language: python
python:
  - "2.7"

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages
  - bash -xve ./test/travis_package_make.bash
  - source ~/catkin_ws/devel/setup.bash
  - export PYTHONPATH=$PYTHONPATH:/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages
  - bash -xve ./test/travis_prepare_dummy_files.bash
  - rostest pimouse_run_corridor wall_stop.launch
  - rostest pimouse_run_corridor wall_stop_accel.launch
